### ISSUE TITLE
Need to Uncheck Allow only local requests

### ISSUE THREAD

**Issue by bmrussell** [chriscrowe/docker-pihole-unbound#102]
Hi Chris

thanks for putting this togther. Much appreciated. It might be worth adding a note to the readme that you'll need to uncheck _Allow only local requests_ in the pihole config? 

Presumably as pihole is on the docker network within the container.

**Comment by SSinSD** [comment]
This can be accomplished by setting this environment variable: DNSMASQ_LISTENING=single

See pull request above.

**Comment by bmrussell** [comment]
Many thanks Chris

**Comment by chriscrowe** [comment]
`DNSMASQ_LISTENING` is now set to `single` by default starting in [2022.02.1-2](https://github.com/chriscrowe/docker-pihole-unbound/releases/tag/2022.02.1-2)
