### ISSUE TITLE
Request: How to Change Default Web Port

### ISSUE THREAD

**Issue by bioszombie** [chriscrowe/docker-pihole-unbound#104]
Team,

Currently, the server that pi-hole is running has multiple docker containers running. One of which is an NGINX web server serving two python flask application. Another docker container is serving a reverse proxy, also NGINX, that forwards traffic from the WAN on port 80 to the respective python flask applications web ports.

When I enable the pi-hole I notice that the WAN traffic on Port 80 is not forwarded. Instead the browser is directed to a whitelist page from pi-hole. However, when disable the pi-hole traffic is forwarded to the correct flask application.

Do you know if its possible to change the default web port on the pi-hole?

**Comment by SSinSD** [comment]
I accomplish this by modifying the port line in docker-compose.yaml from this:
- 80:80/tcp
to this:
- 8080:80/tcp

If your server IP address is x.x.x.x, pointing to x.x.x.x:8080 will now bring up the pi-hole web interface, and pointing to x.x.x.x should point to the other container that is looking for port 80.  Hope this helps.

**Comment by bioszombie** [comment]
This has been resolved. I was able to change the web port without issue. Thank you!

**Comment by chriscrowe** [comment]
New `PIHOLE_WEBPORT ` variable is available for this starting in the [2022.02.1-2](https://github.com/chriscrowe/docker-pihole-unbound/releases/tag/2022.02.1-2) release
