### ISSUE TITLE
High Load

### ISSUE THREAD

**Issue by TheBassfly** [chriscrowe/docker-pihole-unbound#106]
Hey there

My Pihole-Unbound Docker hast an permanent high CPU Load a gets me permanent Error Messages about this high Load.

Ist there anything I can do to set down the load?

Thanks

![Bildschirmfoto 2022-02-22 um 11 21 35](https://user-images.githubusercontent.com/59471393/155112743-48d82a59-74ef-448c-8d51-7b53648c0bb5.png)

**Comment by chriscrowe** [comment]
Sorry but this has nothing to do with this repo, likely you're just overloading your hardware.
