### ISSUE TITLE
Suggestion: could you also create a 'nightly' version which uses the latest pi-hole and unbound version?

### ISSUE THREAD

**Issue by churchofnoise** [chriscrowe/docker-pihole-unbound#110]
Hi Chris,
I used to run Pi-Hole and Unbound natively on RPI but recently got a Firewalla Purple device on which I want to run pi-hole and unbound in a docker container.
I intend to use your one-container solution (thanks for that!!) but was wondering if you could consider a nightly version that contains the latest pi-hole and unbound versions? (I used to run those natively on the rpi)

Thanks for considering!

**Comment by h3rb1n4t0r** [comment]
chris is probably packing the code manually together for the one-container solution. for your case, i'd consider the two-container solution and watchtower for automated update checks in self-defined intervals

**Comment by pluim003** [comment]
It's a while ago, but created a fork yesterday which uses a newer version of Unbound and made a cronjob to make a nighty build using the pihole nightly docker-image. Dunno if it will give advantages but could be, but it could also cause trouble ofcourse. :-)

**Comment by pluim003** [comment]
@churchofnoise , if you're interested a nightly build can be pulled: docker pull pluim003/pihole-unbound:nightly . It has the latest pihole-nightly docker image combined with the latest unbound-version.

**Comment by churchofnoise** [comment]
Thanks for that @pluim003 ! In the mean time, I've adjusted my approach: I'm using a yaml file that leverages both the official nightly docker image of pi-hole and another docker image for Unbound that's kept very well up to date ( https://github.com/klutchell/unbound-docker ). Additional benefit is that it lets me adjust versions for each independently. (and custom config for Unbound is also fairly easy)
Hartelijk bedankt Dick!

**Comment by pluim003** [comment]
You're welcome @churchofnoise . Your original suggestion was over 6 months old and I just started working on this a few days ago (after, as mentioned before, I discovered that it uses an 'old' version of Unbound). I'm not that familiair with Unbound myself. Should dig into this further but that has no priority yet.
