### ISSUE TITLE
Feature Request - Support for Gravity Sync

### ISSUE THREAD

**Issue by bioszombie** [chriscrowe/docker-pihole-unbound#116]
**Gravity Sync**
[https://github.com/vmstan/gravity-sync/wiki/System-Requirements](https://github.com/vmstan/gravity-sync/wiki/System-Requirements)

From their wiki:

> What is better than a [Pi-hole](https://github.com/pi-hole/pi-hole) blocking trackers, advertisements, and other malicious domains on your network? That's right, two Pi-hole blocking all that junk on your network!
> 
> [Seriously. Why two Pi-hole?](https://github.com/vmstan/gravity-sync/wiki/Frequent-Questions#why-do-i-need-more-than-one-pi-hole)[](https://github.com/chriscrowe/docker-pihole-unbound/issues/new#features)
> But if you have more than one Pi-hole in your network you'll want a simple way to keep the list configurations and local DNS settings identical between the two. That's where Gravity Sync comes in. With proper preparation, it should only take a few minutes to install. Ideally you setup Gravity Sync and forget about it -- and in the long term, it would be awesome if the Pi-hole team made this entire script unnecessary.

I have two containerized Pi-Hole installations on their own raspberry pi. I would like to be able to sync my secondary pi to the primary using gravity sync. Per the system requirements Gravity Sync will run on the host machine not inside the container. When running their installer it does not detect the pi-hole instance.

**Comment by chriscrowe** [comment]
This repo does not use the official pihole image, instead I'm building a new image based off the pihole image and installing the Unbound packages (thus the point of this repo).
