### ISSUE TITLE
(network.c.313) can't bind to socket: 192.168.1.2:80 Address already in use 

### ISSUE THREAD

**Issue by Freakaa** [chriscrowe/docker-pihole-unbound#13]
Hi,

I tried your new "one-container" version. The container is starting, but I run into the following loop:

Starting lighttpd
(network.c.313) can't bind to socket: 192.168.1.2:80 Address already in use 
Stopping lighttpd
lighttpd: no process found

My .env file looks like this (ServerIP=Synology IP; REV_SERVER_Target=Fritzbox)

ServerIP=192.168.1.2
TZ=Europe/Berlin
WEBPASSWORD=12345678
REV_SERVER=true
REV_SERVER_DOMAIN=local
REV_SERVER_TARGET=192.168.1.1
REV_SERVER_CIDR=192.168.0.0/16

I don't know, what to do and hope you can help me.

Regards

**Comment by chriscrowe** [comment]
This means your host system is already exposing a service on port 80, so it’s conflicting with the container. More info here:

https://github.com/pi-hole/docker-pi-hole

**Comment by Freakaa** [comment]
Hi Chris,

thanks for your feedback and the link. Then I'll dig a littler bit deeper into this reverse proxy thing, because I couldn't find the guilty app using port 80 :(

ash-4.3# netstat -na | grep 80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN    

Meanwhile I put your "one-container" version into a macvlan and changed the DNS at the fritzbox to the PI-hole IP. Works like a charme :)

One more thing: I do not pass the DNSSEC resolver tests on this webpage ==> https://dnssec.vs.uni-due.de
Is there anything to reconfigure in unbound?

Regards

**Comment by chriscrowe** [comment]
Try this: `sudo lsof -i :80`

**Comment by Freakaa** [comment]
Thanks Chris! The output is:

root@FleasNAS:/# sudo lsof -i :80
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx   12635 root    9u  IPv4  19451      0t0  TCP *:http (LISTEN)
nginx   12635 root   10u  IPv6  19452      0t0  TCP *:http (LISTEN)
nginx   19123 http    9u  IPv4  19451      0t0  TCP *:http (LISTEN)
nginx   19123 http   10u  IPv6  19452      0t0  TCP *:http (LISTEN)
nginx   19124 http    9u  IPv4  19451      0t0  TCP *:http (LISTEN)
nginx   19124 http   10u  IPv6  19452      0t0  TCP *:http (LISTEN)
nginx   19125 http    9u  IPv4  19451      0t0  TCP *:http (LISTEN)
nginx   19125 http   10u  IPv6  19452      0t0  TCP *:http (LISTEN)
nginx   19126 http    9u  IPv4  19451      0t0  TCP *:http (LISTEN)
nginx   19126 http   10u  IPv6  19452      0t0  TCP *:http (LISTEN)

But don't know, which app has running nginx?

**Comment by Freakaa** [comment]
Didn't find a config file, but inside those two files (nginx, nginx.pid) was nothing interesting... :(

root@NAS:/# sudo ps aux | grep nginx
root       794  0.0  0.0  23144  2300 pts/14   S+   20:27   0:00 grep --color=auto nginx
root     12635  0.0  0.2  30880  7740 ?        S<s  12:19   0:00 nginx: master process /usr/bin/nginx -g pid /run/nginx.pid; daemon on; master_process on;
http     19123  0.0  0.2  30884  7888 ?        S<   12:21   0:00 nginx: worker process
http     19124  0.0  0.1  30884  5828 ?        S<   12:21   0:00 nginx: worker process
http     19125  0.0  0.2  30884  8220 ?        S<   12:21   0:00 nginx: worker process
http     19126  0.0  0.2  30884  8344 ?        S<   12:21   0:02 nginx: worker process

**Comment by chriscrowe** [comment]
I've just noticed your hostname is `NAS` -- It's highly likely that your NAS runs a web service by default for managing the NAS itself. I think your best course of action here is to try hosting the Pi-Hole admin interface on another port. Let me do some digging to see if I can expose a variable for that.

**Comment by Freakaa** [comment]
Hi Chris - sorry for the confusion, it's not only "NAS". I deleted my name and posted only "NAS". The real name is "MYNAMENAS".

**Comment by chriscrowe** [comment]
Understood, but is this a NAS that you're trying to install on? If so, it probably runs a web management service which will conflict with the Pi-Hole web management service.

**Comment by Freakaa** [comment]
Yes, it's a DS918+ which I want to install PI-Hole...

I am running the following stuff in Docker:

- ioBroker (Macvlan)
- JDownloader (Bridge)
- TVHeadend (Host)
- Portainer (Bridge)
- Watchtower (Host)
- EmbyServer (Bridge)
- Your PI-Hole one container version (Macvlan at the moment)

And from Synology only the following Apps:

- Docker
- CloudSync
- HyperBackup

But don't know, which of them is running a web management service!?

**Comment by chriscrowe** [comment]
Should be easy enough to find out-- what happens when you punch `http://<nas_ip_address` into your browser? What do you see?

**Comment by Freakaa** [comment]
> Should be easy enough to find out-- what happens when you punch `http://<nas_ip_address>` into your browser? What do you see?

I see the Synology Web Desktop.... funny to reach it without using port 5001...hmmm...

I made a change to use "https" instead of "http" to join the Web Desktop some weeks again - maybe that's the reason...!?

**Comment by chriscrowe** [comment]
Check under Control Panel -> Network -> DSM Settings, I've got my HTTP port set to 5000 and HTTPS set to 5001

**Comment by Freakaa** [comment]
Some here.

There's also checked the following under the DSM-Settings:

- HTTP-Connection automatically to HTTPS
- Activate HTTP/2
- Aktivate "Server"Header.... in HTTP-Answers. Custom-server ==> nginx ; Maybe here's the problem?

**Comment by chriscrowe** [comment]
> * Activate "Server"Header.... in HTTP-Answers. Custom-server ==> nginx ; Maybe here's the problem?

Nope. I really think it's just best to change the Pi-Hole port. Give me some time and I'll investigate that.

**Comment by Freakaa** [comment]
I will - thanks a lot bro!

**Comment by GadgetComa** [comment]
I ran into the same problem on my DS916+. After a bit of searching, it looks like the Pi-Hole admin port can be set via WEB_PORT. I added it to my yaml file and it worked.

**Comment by chriscrowe** [comment]
> I ran into the same problem on my DS916+. After a bit of searching, it looks like the Pi-Hole admin port can be set via WEB_PORT. I added it to my yaml file and it worked.

Good find! Somehow I checked this page the other day for exactly that variable and couldn’t find it 🤦‍♂️

https://hub.docker.com/r/pihole/pihole

**Comment by Freakaa** [comment]
@GadgetComa @chriscrowe thanks - I got working with the WEB_PORT great.

But how do I set my fritzbox? When I point the DNS to my NAS IP, which is also the PI-Hole IP I'm not able to access the internet anymore.

**Comment by GadgetComa** [comment]
Have you allowed port 53 through the firewall on your NAS?

**Comment by chriscrowe** [comment]
> Have you allowed port 53 through the firewall on your NAS?

This is my best guess too.

**Comment by Freakaa** [comment]
Thank you - didn't know, that I have to allow port 53 on the NAS firewall also. 

Now I can access the internet, but Pihole doesn't block anything :(

My env looks like this:

ServerIP=192.168.1.2
TZ=Europe/Berlin
WEBPASSWORD=3214
REV_SERVER=true
REV_SERVER_DOMAIN=local
REV_SERVER_TARGET=192.168.1.1
REV_SERVER_CIDR=192.168.0.0/16
WEB_PORT=8709

What is still wrong?

**Comment by chriscrowe** [comment]
Have you configured your block lists in Pi-Hole? Out of the box it doesn't block a whole lot. Please refer to the Pi-Hole docs. I'll close this issue as it seems you've gotten your original problem resolved.

**Comment by Freakaa** [comment]
Thanks Chris - yes the original problem is solved.

**Comment by Freakaa** [comment]
For all, who want know, why PI-Hole was not blocking anything on my NAS. 
Since I'm using Link Aggregation (bond0), I had to switch to "Listen on all interfaces" under settings in PI-Hole. Now it works perfect! Thanks Chris for the great work and support!
