### ISSUE TITLE
What does the lighttpd-external.conf file do? 

### ISSUE THREAD

**Issue by DanteNahuel** [chriscrowe/docker-pihole-unbound#14]
Hi. Sorry, this is not an Issue but a question. I got here through Reddit and I'm a newbie to Docker and containers, so I'm trying to understand every bit of your solution.
What does the lighttpd-external.conf file achieve? I thought that this was only needed when you had to use another Port because of port conflicts, but I see the code there is not related to that.

**Comment by chriscrowe** [comment]
That file is providing an override to the admin web service to allow viewing it inside an iframe— the default config disallows this. Personally I wanted this so that I could add a Pi-Hole button in my Home Assistant sidebar and view my Pi-Hole embedded in my HA UI.

**Comment by DanteNahuel** [comment]
@chriscrowe thank you for the explanation. So this can be removed or overlooked without any impact to the container's functionality, right?

**Comment by chriscrowe** [comment]
> @chriscrowe thank you for the explanation. So this can be removed or overlooked without any impact to the container's functionality, right?

Yep, correct.
