### ISSUE TITLE
Tag: 2022.07.1 - /usr/bin/sudo

### ISSUE THREAD

**Issue by gitentropy** [chriscrowe/docker-pihole-unbound#145]
Hey,

I've had an issue arise with the latest tag 2022.07.1

Whenever I try to update Gravity or add additional Local DNS entries, I get the below error:

```
sudo: /etc/sudo.conf is world writable
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

I've tried a few troubleshooting methods such as chmod root, but it's frankly out of my depth.

Env setup is below, but I've also done a complete default install with no success.

PIHOLE_GID=100
PIHOLE_UID=1000
DNSMASQ_USER=pihole
PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
phpver=php
PIHOLE_DOCKER_TAG=2022.05
S6_OVERLAY_VERSION=v2.1.0.2
PIHOLE_INSTALL=/etc/.pihole/automated install/basic-install.sh
PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
PHP_ERROR_LOG=/var/log/lighttpd/error.log
IPv6=True
S6_LOGGING=0
S6_KEEP_ENV=1
S6_BEHAVIOUR_IF_STAGE2_FAILS=2
ServerIP=0.0.0.0
FTL_CMD=no-daemon

Issue is present if I have bind/local volumes.

Fully resolve and function normally when reverting to 2022.05

Appreciate all the work, just wanted to highlight an issue incase it's got further impacts.

**Comment by Auxcomb1** [comment]
tengo el mismo problema, lo pudiste solucionar?

**Comment by gitentropy** [comment]
@Auxcomb1 I never solved this, I hoped a later release would fix it but I'm not sure it that ended up being the case.
As I migrated pihole away from docker.
