### ISSUE TITLE
Tag 2022.08.2 => unable to start container

### ISSUE THREAD

**Issue by Volyz** [chriscrowe/docker-pihole-unbound#152]
The image tagged 2022.08.2 is unable to start

1 - Initial stack : 
  Base image : 2022.07.1
  network : ok
  image: running

2 - Pulling new image : 2022.08.2

3 - Updating the stack

4 - Launching the stack results in the image restarting every minute, with no network (ip address), published ports etc etc

Logs are as follow : 

```
No log line matching the '' filter
```

The container appears to be frozen and unresponsive

Solution => reverting to 2022.07.1 tag

**Comment by chriscrowe** [comment]
See https://github.com/chriscrowe/docker-pihole-unbound/issues/154

**Comment by Volyz** [comment]
Devices : Pine64
Platform : Armbian 22.08.1 Focal with Linux 5.15.48-sunxi64

System updated and upgraded

docker logs show only

```
No log line matching the '' filter
```

no logs are written ( no s6-svscan or anything ) other than just the line i gave you which is weird.

I'll stick to 2022.07.1 for the moment until i dig more or see something else but it's not the #154 symptoms and solution for me

**Comment by Volyz** [comment]
2022.09.3 works
