### ISSUE TITLE
New docker tag 2022.08.3 has been released :-(

### ISSUE THREAD

**Issue by corasaniti** [chriscrowe/docker-pihole-unbound#156]
I'm sorry to inform you that the new docker tag 2022.08.3 has been released.
You should do a new build :-(

**What's Changed**
Test for empty values in the PIHOLE_DNS_ array, skip if it's empty by @PromoFaux in https://github.com/pi-hole/docker-pi-hole/pull/1185
Tweaks to s6 service startup order to clarify logged output by @PromoFaux in https://github.com/pi-hole/docker-pi-hole/pull/1191
Prevent S6 timeouts on container start by setting S6_CMD_WAIT_FOR_SERVICES_MAXTIME to 0 by @PromoFaux in https://github.com/pi-hole/docker-pi-hole/pull/1192
Set FTL/DNSMASQ listening behaviour per variable if it is set by @PromoFaux in https://github.com/pi-hole/docker-pi-hole/pull/1193

Thank you
PC

**Comment by corasaniti** [comment]
@chriscrowe 
Hi, please can you do a new build with the tag `2022.08.3`? 
Thanks in advance

**Comment by corasaniti** [comment]
New docker tag is available `2022.09.1` :-(
Thanks

**Comment by louis-manabat** [comment]
> New docker tag is available `2022.09.1` :-(
> Thanks 
> 

Awaiting for PR to be accepted for tag `2022.09.1` :)

**Comment by chriscrowe** [comment]
Working on 2022.09.3 release now.

**Comment by corasaniti** [comment]
@chriscrowe 
Thanks
