### ISSUE TITLE
Unbound does not start after 2022.08.2

### ISSUE THREAD

**Issue by tokenize47** [chriscrowe/docker-pihole-unbound#157]
After the update to 2022.08.2 I have the following error in the logs:

```
s6-supervise unbound (child): fatal: unable to exec run: Permission denied
s6-supervise unbound: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise unbound (child): fatal: unable to exec run: Permission denied
s6-supervise unbound: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise unbound (child): fatal: unable to exec run: Permission denied
```

I guess it's related with the s6 v3 update?

Thanks in advance

**Comment by patrick1357** [comment]
Had the same issue.

I added the following command to the Dockerfile to fix the issue.
`RUN chmod 774 /etc/services.d/unbound/run`

My complete Dockerfile looks like this:

```
FROM pihole/pihole:latest

RUN apt update && apt install -y unbound

#COPY lighttpd-external.conf /etc/lighttpd/external.conf 
COPY unbound-pihole.conf /etc/unbound/unbound.conf.d/pi-hole.conf
COPY 99-edns.conf /etc/dnsmasq.d/99-edns.conf

RUN mkdir -p /etc/services.d/unbound
COPY unbound-run /etc/services.d/unbound/run
#Added workaround
RUN chmod 774 /etc/services.d/unbound/run

ENTRYPOINT ./s6-init
```

I hope that this is helpful

**Comment by tokenize47** [comment]
Thanks for the help.

With your workaround I get a different error now:

```
s6-supervise unbound (child): fatal: unable to exec run: No such file or directory
s6-supervise unbound: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise unbound (child): fatal: unable to exec run: No such file or directory
s6-supervise unbound: warning: unable to spawn ./run - waiting 10 seconds
```
Any ideas?

**Comment by DKeppi** [comment]
I had the same issue with 2022.08, before chriscrowe released his new version here. 
Did you also changed the first line in the unbound-run file to

#!/command/with-contenv bash

**Comment by corasaniti** [comment]
please can you do a new build with the tag `2022.08.3`? 
Thanks in advance

**Comment by tokenize47** [comment]
> I had the same issue with 2022.08, before chriscrowe released his new version here. Did you also changed the first line in the unbound-run file to `#!/command/with-contenv bash`?
> 
> Here you see all changes he made: [8c1172a](https://github.com/chriscrowe/docker-pihole-unbound/commit/8c1172acbc33d8ff7940ce4fd61ced5de02b5049)

I forgot the /command change, that was it! I got it working now with 2022.08.3, thanks!

**Comment by tokenize47** [comment]
> please can you do a new build with the tag `2022.08.3`? Thanks in advance

Only the repo owner can do that. You can also just clone the repo and build the image yourself.

**Comment by corasaniti** [comment]
@tokenize47 
I would like to do a build for both raspberry armv7 and amd64 but I have never used tool docker build x for cross platforms ... :-(
