### ISSUE TITLE
Portainer Stack Issue

### ISSUE THREAD

**Issue by rbretmounet** [chriscrowe/docker-pihole-unbound#162]
I have successfully deployed the stack for pi-hole but using the IP I use to access the web interface doesn't seem to be working when I change my DNS to it.

**Comment by MaHl111** [comment]
**Then you most likely didn't deploy it successfully.**

With all seriousness, there isn't much to go off of when you don't provide any information or actions you took. 
If you want to make sure your device uses correct DNS, type command `nslookup example.com` in to your terminal, it will return   address, which should be Local IP of your Pihole device. If that's not the case, your network is not using your Pihole as DNS.

To get more help, you need to provide more details.

**Comment by rbretmounet** [comment]
I created a stack in portainer by copying and pasting the yml file into the webstack section. I then specified all the env variables. I may just be confused about what IP I use is it the docker container IP or the computer's IP Portainer is running on?

**Comment by rbretmounet** [comment]
Update: I can have queries go through the pihole but only when they are done with the 172.18.0.2 IP and from the same machine.
