### ISSUE TITLE
error on DNSMASQ

### ISSUE THREAD

**Issue by Bigua** [chriscrowe/docker-pihole-unbound#163]
Hi
i'm keep geting this error after start:  

`ignoring query from non-local network 192.168.0.116 (logged only once)
`

here's my .env

```
FTLCONF_REPLY_ADDR4=192.168.0.100
TZ=America/Sao_Paulo
WEBPASSWORD=senha01
HOSTNAME=pihole
DOMAIN_NAME=pihole.local
PIHOLE_WEBPORT=80
WEBTHEME=default-dark
REV_SERVER=true
REV_SERVER_DOMAIN=local
REV_SERVER_TARGET=192.168.0.1
REV_SERVER_CIDR=192.168.0.1/16
```

what I Am done wrong?

btw, i am running this on a rasp 4, but dont think its related.

thanks in advance

**Comment by a4orce84** [comment]
I am seeing the same issue. The IP it is complaining about is my router though:

"ignoring query from non-local network 10.0.1.1 (logged only once)"

Thanks!

**Comment by danieled-it** [comment]
The easy fix would be to enable FTL to listen to all requests:

![image](https://user-images.githubusercontent.com/19713668/191045187-4f128b73-84db-4de4-bd7f-6e351c60c3b8.png)

If you want to avoid this "potential security risk" (it all depends if your DNS listener is exposed outside your local network) then we'd need to see a bit of your Docker config, including the port mapping you're applying and so on

**Comment by Bigua** [comment]
> The easy fix would be to enable FTL to listen to all requests:
> 
> ![image](https://user-images.githubusercontent.com/19713668/191045187-4f128b73-84db-4de4-bd7f-6e351c60c3b8.png)
> 
> If you want to avoid this "potential security risk" (it all depends if your DNS listener is exposed outside your local network) then we'd need to see a bit of your Docker config, including the port mapping you're applying and so on

Worked!! thanks =)
