### ISSUE TITLE
Pihole updates? 2 versions behind

### ISSUE THREAD

**Issue by cyanide699** [chriscrowe/docker-pihole-unbound#164]
Hi.. This is now 2 revisions of pihole behind... Is it possible to add support for pihole -up command to save waiting on updated image in future?

Thanks

**Comment by chriscrowe** [comment]
`pihole -up` and Docker are incompatible because containers are ephemeral by definition. Even if you managed to update pihole inside the container it would revert back on the next restart.

**Comment by cyanide699** [comment]
Ok Thanks
