### ISSUE TITLE
Broken with pihole 4.3?

### ISSUE THREAD

**Issue by HorstBrack75** [chriscrowe/docker-pihole-unbound#2]
Thanks for the work. It worked great until now.
I now wanted to set-up on a new Synology and I don´t manage to get the pihole container to start.

ERROR: for pihole  Cannot start service pihole: Bind mount failed: '/volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf' does not exists
ERROR: Encountered errors while bringing up the project.

ERROR: for pihole  Cannot start service pihole: Bind mount failed: '/volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf' does not exists
ERROR: Encountered errors while bringing up the project.

Am I doing something wrong? Do I need to revert to an older revision of pihole maybe?

THX

**Comment by HorstBrack75** [comment]
> Thanks for the work. It worked great until now.
> I now wanted to set-up on a new Synology and I don´t manage to get the pihole container to start.
> 
> ERROR: for pihole Cannot start service pihole: Bind mount failed: '/volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf' does not exists
> ERROR: Encountered errors while bringing up the project.
> 
> ERROR: for pihole Cannot start service pihole: Bind mount failed: '/volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf' does not exists
> ERROR: Encountered errors while bringing up the project.
> 
> Am I doing something wrong? Do I need to revert to an older revision of pihole maybe?
> 
> THX

I created a "resolv.conf" file and added that did the trick.

**Comment by chriscrowe** [comment]
Glad you found the solution 👍
