### ISSUE TITLE
Usage guidance

### ISSUE THREAD

**Issue by kevindd992002** [chriscrowe/docker-pihole-unbound#20]
So I'm using the pihole/pihole official container and want to transition to using your container because of Unbound. I have some questions before I do that:

1. I'm on 5.2.2. Would using the same etc-pihole and etc-dnsmasq.d config folders for your container work just fine?
2. In the new "one container" version of your container, why would you not need macvlan anymore? I use macvlan so that pihole has its own IP address. I don't want it sharing the host IP address because it is a critical service in the network and I just prefer it that way.

Thanks in advance for your help.

**Comment by chriscrowe** [comment]
Disclaimer ahead of time-- back up everything just in case, before you make this transition.

> 1. I'm on 5.2.2. Would using the same etc-pihole and etc-dnsmasq.d config folders for your container work just fine?

Yes that should work just fine.

> 2. In the new "one container" version of your container, why would you not need macvlan anymore? I use macvlan so that pihole has its own IP address. I don't want it sharing the host IP address because it is a critical service in the network and I just prefer it that way.

I was simply trying to simplify the configs since `macvlan` is somewhat of an advanced Docker concept. You're free to continue using it if you know how!

**Comment by kevindd992002** [comment]
> 
> 
> Disclaimer ahead of time-- back up everything just in case, before you make this transition.
> 
> > 1. I'm on 5.2.2. Would using the same etc-pihole and etc-dnsmasq.d config folders for your container work just fine?
> 
> Yes that should work just fine.
> 
> > 1. In the new "one container" version of your container, why would you not need macvlan anymore? I use macvlan so that pihole has its own IP address. I don't want it sharing the host IP address because it is a critical service in the network and I just prefer it that way.
> 
> I was simply trying to simplify the configs since `macvlan` is somewhat of an advanced Docker concept. You're free to continue using it if you know how!

I see. Thanks for the confirmation. I'm still curious though. How does combining the two containers into one "not need" macvlan anymore?
