### ISSUE TITLE
Please add it to CasaOS

### ISSUE THREAD

**Issue by hqnicolas** [chriscrowe/docker-pihole-unbound#207]
i'm using CasaOS
My Router is 192.168.0.1
My CasaOS is 192.168.0.28
tested, and Runing Amazing

pihole.json

`{"host":"http://192.168.0.28/","protocol":"http","port_map":"35737","cpu_shares":90,"restart":"unless-stopped","label":"pihole","position":false,"index":"/admin","icon":"https://icon.casaos.io/main/all/pihole-unbound.png","network_model":"downloads_default","image":"cbcrowe/pihole-unbound:latest","description":"","origin":"local","ports":[{"container":"53","host":"53","protocol":"tcp","desc":"","type":0},{"container":"53","host":"53","protocol":"udp","desc":"","type":0},{"container":"80","host":"35737","protocol":"tcp","desc":"","type":0},{"container":"443","host":"443","protocol":"tcp","desc":"","type":0}],"volumes":[],"envs":[{"container":"FTLCONF_LOCAL_IPV4","host":"192.168.0.28","desc":"","type":0},{"container":"TZ","host":"America/Sao_Paulo","desc":"","type":0},{"container":"WEBPASSWORD","host":"QWERTY1234password","desc":"","type":0},{"container":"WEBTHEME","host":"default-light","desc":"","type":0},{"container":"REV_SERVER","host":"true","desc":"","type":0},{"container":"REV_SERVER_TARGET","host":"192.168.0.1","desc":"","type":0},{"container":"REV_SERVER_DOMAIN","host":"local","desc":"","type":0},{"container":"REV_SERVER_CIDR","host":"192.168.0.0/16","desc":"","type":0},{"container":"PIHOLE_DNS_","host":"127.0.0.1#5335","desc":"","type":0},{"container":"DNSSEC","host":"\"true\"","desc":"","type":0},{"container":"DNSMASQ_LISTENING","host":"single","desc":"","type":0},{"container":"PATH","host":"/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","desc":"","type":0},{"container":"phpver","host":"php","desc":"","type":0},{"container":"PHP_ERROR_LOG","host":"/var/log/lighttpd/error-pihole.log","desc":"","type":0},{"container":"IPv6","host":"True","desc":"","type":0},{"container":"S6_KEEP_ENV","host":"1","desc":"","type":0},{"container":"S6_BEHAVIOUR_IF_STAGE2_FAILS","host":"2","desc":"","type":0},{"container":"S6_CMD_WAIT_FOR_SERVICES_MAXTIME","host":"0","desc":"","type":0},{"container":"FTL_CMD","host":"no-daemon","desc":"","type":0},{"container":"DNSMASQ_USER","host":"pihole","desc":"","type":0}],"devices":[],"cap_add":[],"cmd":[],"privileged":false,"host_name":"pihole","container_name":"pihole","appstore_id":0,"custom_id":"8e669873-4760-47b1-aacd-fec95f166f3a","enable_upnp":false,"version":"1.0"}`

**Comment by qatar2030** [comment]
I have zimaboard with casaos can you please help me how to do that? I always get an error

**Comment by hqnicolas** [comment]
![You-dumb-ass-hole](https://github.com/chriscrowe/docker-pihole-unbound/assets/41456803/c9110efd-e041-49e9-bca3-853d9f0ada12)

![You-dumb-ass-hole++](https://github.com/chriscrowe/docker-pihole-unbound/assets/41456803/f5247f37-697e-4f40-81fa-d366afbe5d2f)

![You-dumb-ass-hole++3](https://github.com/chriscrowe/docker-pihole-unbound/assets/41456803/74827ed8-4bfb-4222-bcac-dcda23ee1535)

![You-dumb-ass-hole++4](https://github.com/chriscrowe/docker-pihole-unbound/assets/41456803/08d1eadc-3684-4114-bbbf-95fc22f8a84f)


[im-dumb.json](https://github.com/chriscrowe/docker-pihole-unbound/files/13232378/im-dumb.json)
