### ISSUE TITLE
network_mode: "host"

### ISSUE THREAD

**Issue by loopwert** [chriscrowe/docker-pihole-unbound#21]
From what I have read with host mode you can not change the ports for the docker i.e 8080:80. Is there something i am missing? Forgive my ignorance.

**Comment by chriscrowe** [comment]
Good catch-- when using host networking those port remappings are ignored:

https://docs.docker.com/network/host/

I have removed the remaps in [v5.6](https://github.com/chriscrowe/docker-pihole-unbound/releases/tag/v5.6)
