### ISSUE TITLE
[Issue] DockerFile: Typo on start unbound

### ISSUE THREAD

**Issue by diamant-x** [chriscrowe/docker-pihole-unbound#22]
On the one-container [dockerfile](https://github.com/chriscrowe/docker-pihole-unbound/blob/master/one-container/pihole-unbound/Dockerfile) you still point to the old named file "install_unbound", but apparently this file was renamed lately to "run_unbound".
This makes it to fail if you try to run the dockerfile directly through file not found error.

Thanks!

PD: It should be easier to fix for you than the whole process of submitting a PR

**Comment by chriscrowe** [comment]
Good catch, could swear I updated that before... Fixed now.
