### ISSUE TITLE
Repo/Image no longer maintained? ⏳

### ISSUE THREAD

**Issue by origamiofficial** [chriscrowe/docker-pihole-unbound#236]
Hi @chriscrowe ,

I hope you're doing well! I just wanted to check in and see if you had any plans for updating your pihole-unbound docker image soon It seems like it hasn't seen an update in a while, and I know folks using it might be missing out on some potential improvements.

Speaking of improvements, I've been actively maintaining my own docker image for Pi-hole+Unbound at https://github.com/origamiofficial/docker-pihole-unbound. 

It might be a good alternative for users looking for:

* Regular updates: I aim to push updates with the latest Pi-hole and Unbound by checking for updates daily to ensure optimal performance and security.
* Flexibility: My image provides a wider range of tags, including `latest`, `dev`, and `development-v6`, to cater to different workflow needs of early birds.
* Cross-platform support: My image runs smoothly on multiple platforms, giving users more deployment options like: `amd64`, `arm64`, `armhf`, `armel` and the `i386` coming soon.

I understand you have your own approach to building and maintaining the image, and I certainly respect that. My intention here is simply to offer another option for the community and make sure everyone has access to the latest and greatest Pi-hole experience.

If you're ever interested in collaborating or comparing notes, I'd be happy to chat!

Best regards,
@origamiofficial

**Comment by tineambracken** [comment]
Hi @chriscrowe - I'd like to know the answer also.  

Thanks in advance, 
Christine

**Comment by a4orce84** [comment]
Following as well....thank you!

**Comment by xinput** [comment]
would like to know if it's still maintained as well.
thanks

**Comment by Wuemeli** [comment]
Same here

**Comment by chriscrowe** [comment]
I just made a new release recently

**Comment by hqnicolas** [comment]
I'm using the cbcrowe/pihole-unbound:2023.05.2
Please keel the legacy!
was amazing

**Comment by XxxSpiritvsxxX** [comment]
Is this abandoned?
