### ISSUE TITLE
Pi-hole password

### ISSUE THREAD

**Issue by mlopezcoria** [chriscrowe/docker-pihole-unbound#24]
I followed the README 'guide' to install this, but when I run `docker logs pihole | grep random` I get this error:

`[1612393931] unbound[17:0] warning: so-rcvbuf 1048576 was not granted. Got 360448. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.`

I'm trying to use the one-container version, by the way.

**Comment by chriscrowe** [comment]
You should specify your password in the `.env` file by specifying a `WEBPASSWORD` variable.

**Comment by mlopezcoria** [comment]
Thank you. But that's what the documentation states, isn't it?
