### ISSUE TITLE
Possibility to preserve standard voumes?

### ISSUE THREAD

**Issue by eisengrau** [chriscrowe/docker-pihole-unbound#25]
Hello,

Is it possible to preserve the standard volume paths, as in the oficial pihole container's compose defaults?

      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'

Should be the paths, as default. It would be beneficial as other services might not detected pihole running on the host, ef the very nice: https://github.com/vmstan/gravity-sync

Could be related to ( #10 ).

Thank You,

**Comment by chriscrowe** [comment]
Not sure if I understand the question. Those paths are already configured as persistent named volumes in the docker-compose config file:

https://github.com/chriscrowe/docker-pihole-unbound/blob/master/one-container/docker-compose.yaml#L29

**Comment by eisengrau** [comment]
Absolutely, understood. It would be just a cosmetic thing: if possible set the default host mapping in that yamls file, instead of etc_pihole-unbound to %default_host_specific_docker_config_files%/etc-pihole/ or ./etc-pihole/:

Of course, It can be modified by hand. For people just copy-pasting, or git cloning your script. This way, other running containers, or host application expecting to detect a pi-hole installation or dnsmasq.conf will find the configs.

**Comment by chriscrowe** [comment]
> Absolutely, understood. It would be just a cosmetic thing: if possible set the default host mapping in that yamls file, instead of etc_pihole-unbound to %default_host_specific_docker_config_files%/etc-pihole/ or ./etc-pihole/:
> 
> Of course, It can be modified by hand. For people just copy-pasting, or git cloning your script. This way, other running containers, or host application expecting to detect a pi-hole installation or dnsmasq.conf will find the configs.

Still not sure if I understand the proposed change. If you think it's backwards compatible with other installations then feel free to submit a pull request and I'll test it 👍
