### ISSUE TITLE
Error in Docker-Compose.yml Networks

### ISSUE THREAD

**Issue by tyrellm04** [chriscrowe/docker-pihole-unbound#29]
Hello,

I'm having issues running this build in a multi-container environment that uses macvlans to make each container accessible directly on the network. Below is the compose section that I'm getting errors on. The shell is saying:

"yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yml", line 23, column 7
could not find expected ':'
  in "./docker-compose.yml", line 24, column 7"
  
  Compose section that I'm trying to run is:
  
  "services:
    pihole_UF1:
    container_name: pihole_UF1
    image: cbcrowe/pihole-unbound:latest
    hostname: piholeUF1
    domainname: piholeUF1.local
    Expose:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 80/tcp
      - 22/tcp # Uncomment to enable SSH
    environment:
      #ServerIP: ${ServerIP}
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: '**_PASSWORD_REDACTED_**'
      #REV_SERVER: ${REV_SERVER}
      #REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      #REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      #REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      DNS1:127.0.0.1#5335
      DNS2:127.0.0.1#5335
      DNSSEC: "true" # Enable DNSSEC
    network_mode: "Bridge"
        networks:
            pi_vlan:
                IPv4_address: 10.10.90.2
    volumes:
      - etc_pihole-unbound:/etc/pihole_UF1:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d_UF1:rw
    restart: unless-stopped"

Any help would be appreciated. This is my first experience with docker compose... So I apologize ahead of time for any noob questions I may have.

**Comment by tyrellm04** [comment]
I realize that killed the indenting... Trying again with the code block. I also corrected a couple of slight indenting issues, but it keeps telling me that the static IP information is invalid. (I commented out the expose because it told me that it wasn't valid either).

"ERROR: The Compose file './docker-compose.yml' is invalid because:
services.pihole_UF1.networks.pi_vlan contains unsupported option: 'IPv4_address'
services.piholeUF2.networks.pi_vlan contains unsupported option: 'IPv4_address'"


YAML below: 

`version: "3"

services:

    pihole_UF1:
        container_name: pihole_UF1
        image: cbcrowe/pihole-unbound:latest
        hostname: piholeUF1
        domainname: piholeUF1.local
        # Expose:
        # - "443"
        # - "53"
        # - "80"
        # - "22" # Uncomment to enable SSH
        environment:
          #ServerIP: ${ServerIP}
          TZ: 'America/Los_Angeles'
          WEBPASSWORD: '**PASSWORD_REDACTED**'
          #REV_SERVER: ${REV_SERVER}
          #REV_SERVER_TARGET: ${REV_SERVER_TARGET}
          #REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
          #REV_SERVER_CIDR: ${REV_SERVER_CIDR}
          DNS1: 127.0.0.1#5335
          DNS2: 127.0.0.1#5335
          DNSSEC: "true" # Enable DNSSEC
        network_mode: "Bridge"
        networks:
            pi_vlan:
                IPv4_address: 10.10.90.2
        volumes:
          - etc_pihole-unbound:/etc/pihole_UF1:rw
          - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d_UF1:rw
        restart: unless-stopped
  
    piholeUF2:
        container_name: piholeUF2
        image: cbcrowe/pihole-unbound:latest
        hostname: piholeUF2
        domainname: piholeUF2.local
        # Expose:
        # - "443"
        # - "53"
        # - "80"
        # - "22" # Uncomment to enable SSH
        environment:
          #ServerIP: ${ServerIP}
          TZ: 'America/Los_Angeles'
          WEBPASSWORD: '**PASSWORD_REDACTED**'
          #REV_SERVER: ${REV_SERVER}
          #REV_SERVER_TARGET: ${REV_SERVER_TARGET}
          #REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
          #REV_SERVER_CIDR: ${REV_SERVER_CIDR}
          DNS1: 127.0.0.1#5335 # Hardcoded to Local Unbound server
          DNS2: 127.0.0.1#5335
          DNSSEC: "true" # Enable DNSSEC
        network_mode: "Bridge"
        networks:
            pi_vlan:
                IPv4_address: 10.10.90.3
        volumes:
          - etc_pihole-unbound:/etc/pihole_UF2:rw
          - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d_UF2:rw
        restart: unless-stopped`

**Comment by chriscrowe** [comment]
Looks like you've got invalid YAML syntax in your `networks:` block-- you need to add `- ` to the items in that list. You can use a YAML linter like [this one](http://www.yamllint.com) to validate your syntax before trying to deploy
