### ISSUE TITLE
Pihole-Unbound single container shows "INSECURE" status

### ISSUE THREAD

**Issue by uhsa779** [chriscrowe/docker-pihole-unbound#32]
I just installed this version via portainer docker. 

Here's my config:

version: '2'

services:
  pihole:
    container_name: pihole-unbound
    image: cbcrowe/pihole-unbound:latest
    hostname: Unbound-pi
    domainname: pihole.local
    ports:
      - 943:443/tcp
      - 53/tcp
      - 53/udp
      - 880:80/tcp
      # - 22/tcp # Uncomment to enable SSH
    environment:
      ServerIP: ${ServerIP}
      TZ: America/Chicago
      WEBPASSWORD: xxxx
      REV_SERVER: 
      REV_SERVER_TARGET: 
      REV_SERVER_DOMAIN: local
      REV_SERVER_CIDR: 
      DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
    network_mode: "host"
    volumes:
      - /home/mythtv/dPi/etc:/etc/pihole:rw
      - /home/mythtv/dPi/dnsmasq:/etc/dnsmasq.d:rw
    restart: unless-stopped

It is up, running - however, under query log, I see ton's of "INSECURE" messages. Is this normal? Is this how it's supposed to be? 

This is my secondary Pi/Unbound. My first one is dedicated box with ubuntu - and that one doesn't have a single INSECURE.

![image](https://user-images.githubusercontent.com/79544342/109686846-45922700-7b48-11eb-9d79-e842b185364c.png)

**Comment by noblesigma** [comment]
Same issue.

**Comment by DKeppi** [comment]
Im not sure if its necessary to have DNSSEC enabled in pihole when you use it with unbound as DNS, because unbound is doing DNSSEC for you. But would be nice to see SECURE, BOGUS, UNSECURE from unbound in pihole query log ;)

**Comment by uhsa779** [comment]
> Im not sure if its necessary to have DNSSEC enabled in pihole when you use it with unbound as DNS, because unbound is doing DNSSEC for you. But would be nice to see SECURE, BOGUS, UNSECURE from unbound in pihole query log ;)

That may have worked - will have to see for the next few hours! Thanks for pointing out the obvious!

**Comment by DKeppi** [comment]
You could check easy if your dnssec works:
http://www.dnssec-or-not.com/

Found some threads about dnssec, pihole and unbound also:

https://discourse.pi-hole.net/t/add-support-for-proxy-dnssec-display-dnssec-info/25936

https://discourse.pi-hole.net/t/pi-hole-unbound-dnsmasq-cache-enabled-or-disabled/27150/2

**Comment by Freakaa** [comment]
> You could check easy if your dnssec works:
> http://www.dnssec-or-not.com/
> 
> Found some threads about dnssec, pihole and unbound also:
> 
> https://discourse.pi-hole.net/t/add-support-for-proxy-dnssec-display-dnssec-info/25936
> 
> https://discourse.pi-hole.net/t/pi-hole-unbound-dnsmasq-cache-enabled-or-disabled/27150/2

I fail every DNSSEC Test... how about you? 
What kind of settings do I need to set on Piholes DNS-settings (Advanced DNS settings) page?

**Comment by DKeppi** [comment]
My Pihole passed the test!

I only use the Conditional Forwarding in Advanced Settings, but that is optional. 
DNSSEC is not ticked because unbound does that already.

DNS is 127.0.0.1#5335 and i use „Listen on all interfaces, permit all origins“

**Comment by Freakaa** [comment]
> My Pihole passed the test!
> 
> I only use the Conditional Forwarding in Advanced Settings, but that is optional.
> DNSSEC is not ticked because unbound does that already.
> 
> DNS is 127.0.0.1#5335 and i use „Listen on all interfaces, permit all origins“

Hmmm... strange. I'm having almost the same settings...

I'm also using the conditional forwarding to my fritz.box, DNS 127.0.0.1#5335 and "Listen on all interfaces".
"Never forward non-FQDNs", "Never forward reverse lookups for private IP ranges" and "Use DNSSEC" are unchecked.

What could be wrong?

**Comment by chriscrowe** [comment]
Not totally sure about the appropriate DNSSEC settings to be honest, but below is what I'm using and DNSSEC tests pass for me:

- DNSSEC enabled
- Conditional Forwarding enabled
- Listen only on interface eth0

Closing this issue as it's not related to the Docker configs provided by the repo.
