### ISSUE TITLE
nginx reverse proxy as webserver ?

### ISSUE THREAD

**Issue by Rar9** [chriscrowe/docker-pihole-unbound#34]
by default pihole comes with lighttpd for webserver

Is it possible deactivate lighttpd and only use nginx reverse proxy?

If so how?

https://docs.pi-hole.net/guides/webserver/nginx/

**Comment by chriscrowe** [comment]
Based on your other issue it sounds like you want to be able to modify the `lighttpd.conf` file -- this can be done by adding another volume to your deployment mapping to the `/etc/lighttpd/` path -- then modifying any files inside that folder will persist across container stops and starts.

**Comment by Rar9** [comment]
No i actually what to fully DISABLE lighttpd as nginx can handle the same FASTER.

**Comment by chriscrowe** [comment]
Gotcha-- Sorry I don't have experience doing that.
