### ISSUE TITLE
Unable to Update from Pi-hole UI

### ISSUE THREAD

**Issue by isaacrlevin** [chriscrowe/docker-pihole-unbound#42]
When I try to add settings from the Pi-hole UI, I get this error

>   Error, something went wrong!
While executing: attempt to write a readonly database
Added 0 out of 1 adlists

Looking at the file permissions inside the container I see

![image](https://user-images.githubusercontent.com/8878502/113330476-9f1a7c80-92d3-11eb-9bf9-1c4411aedac1.png)

I have looked at the persmissions and tried a few installs. Pi-hole and unbound seem to be working but I am unable to update the UI

**Comment by VarunBatraIT** [comment]
I am not sure if this is typo or not - but resolv.conf has 127.0.0.11

Error is 

```
root@pihole:/# pihole -g
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 86
```

```
root@pihole:/# cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```

I created a file and put it as volume with content and config as following and it worked:

```
cat pihole/config/resolv.conf 
nameserver 127.0.0.1
options ndots:0

```


```
        volumes:
           ...
            - ./pihole/config/resolv.conf:/etc/resolv.conf

```


Result:


```
 pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 84233 domains
  [i] List stayed unchanged

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 84233 (84233 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is listening
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
```

**Comment by chriscrowe** [comment]
Updating settings from my UI works just fine (and seemingly for others). I checked my permissions in `/etc/pihole` and they seem to match. Did you change any of the docker/config files?

**Comment by tobyh** [comment]
I'm able to change settings in the pihole web UI, adding a blocklist for example. Like @VarunBatraIT above though, I'm unable to then update gravity. Not sure if that's what @isaacrlevin was originally referring to or not.

I have 127.0.0.11 in /etc/resolv.conf too. Changing that to 127.0.0.1 seems to have everything working correctly.

**Comment by jeff47** [comment]
I don't think editing resolv.conf in the container is a durable solution, because it won't persist if the container is restarted.  However, you can add a DNS line to your docker/docker-compose section which will take care of it.

eg:
`services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: pi
    domainname: pi.local
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    dns:
        - "127.0.0.1"`
      
etc...
