### ISSUE TITLE
unbound warning, sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.

### ISSUE THREAD

**Issue by dokbua** [chriscrowe/docker-pihole-unbound#45]
docker-compose logs report this warning:

`pihole    | [1617699480] unbound[18:0] warning: so-rcvbuf 1048576 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.`

How can I fix that?

**Comment by noblesigma** [comment]
Same issue here, it isn't working anymore.

**Comment by tillcash** [comment]
Comment / Remove the line ` so-rcvbuf: 1m` in unbound conf file to resolve the issue.

**Comment by DKeppi** [comment]
Same Warning i mentioned, a time ago, here: 
#28

**Comment by chriscrowe** [comment]
See comments on above pull request that I ended up closing. This warning is benign, I'm going to leave the directive in the config.

**Comment by NeoPlayer13** [comment]
> Comment / Remove the line ` so-rcvbuf: 1m` in unbound conf file to resolve the issue.

This works if you are not interested in using `DNSSEC`, if you add the line `auto-trust-anchor-file` to the `pi-hole.conf` file, the container runs normally the first time you run it, it shows the error once or twice then just skips it and starts to run normally, but after a reboot it would get stuck showing the error in a loop.
In this instance this error loop disables completely all the unbound capabilities.
