### ISSUE TITLE
How to set DHCP server correctly?

### ISSUE THREAD

**Issue by Ani4aa** [chriscrowe/docker-pihole-unbound#51]
Hi, I'm new with using docker. I decided to ask here cuz I coud not find the solution anywhere. So I tested that pihole-unbound one-container build and it works really good, but my router in DHCP settings haven't got option to put custom DNS server, so I have to turn on somehow DHCP at the container. There is a problem - when I'm starting DHCP server the container keeps restarting, PiHole page is working but it can't connect with network. I think I'm doing sth wrong so. I'm looking for a solution to set up DHCP server correctly. I'm using macvlan to have specific address IP for my ph. I don't understand how it's working - maybe if I had known I would do it. Can someone explain me it if could? (Sorry for my english, if there are any mistakes)

**Comment by chriscrowe** [comment]
Running a DHCP server in Pi-Hole on Docker is a bit complex and requires some extra steps, admittedly I've never done it but you should reference the docs [here](https://hub.docker.com/r/pihole/pihole) and [here](https://docs.pi-hole.net/docker/DHCP/)

Note also that it seems there are some options that must be turned on in the Docker config to support DHCP

<img width="779" alt="image" src="https://user-images.githubusercontent.com/425808/119922869-87532380-bf25-11eb-9f3b-20e2f9f0ea9f.png">
<img width="813" alt="image" src="https://user-images.githubusercontent.com/425808/119922878-8cb06e00-bf25-11eb-9abb-f7424419b20c.png">
