### ISSUE TITLE
docker-compose uses port 53 for PI hole dns but does not expose 5335 for unbound

### ISSUE THREAD

**Issue by chronicblondiee** [chriscrowe/docker-pihole-unbound#52]
Hi,

I was giving this project a go and its really clean single container DNS solution,

One thing that could be nice to have is to add port 5335 for unbound in docker compose with a comment similar to the one you have for ssh so your local server can query unbound directly this is easy for most people familiar with docker but new users might try query dig github.com @127.0.0.1 -p 5335

and wounder why you can't query local dns just something that I didn't release till i looked back over the ports so i just connected to the container and did a dig query inside it to verify

**Comment by chriscrowe** [comment]
Merged
