### ISSUE TITLE
can't update WEBPASSWORD

### ISSUE THREAD

**Issue by gsiawGH** [chriscrowe/docker-pihole-unbound#58]
I change the WEBPASSWORD in the docker-pihole-unbound/one-container/.env file. then run "docker-compose up -d" to start. 
but the password is never changed, I must use the example password.  am I doing something wrong?

however, if I change the HOSTNAME in the .env file, I can see that changes when I log in. but yet the WEBPASSWORD does not get updated.

**Comment by gsiawGH** [comment]
however, if I change the HOSTNAME in the .env file, I can see that changes when I log in. but yet the WEBPASSWORD does not get updated.

**Comment by chriscrowe** [comment]
Sorry without more info about your config files I can't really help here-- if you follow the instructions in the repo it will work just fine.
