### ISSUE TITLE
unbound exec user process caused: exec format error

### ISSUE THREAD

**Issue by asyba** [chriscrowe/docker-pihole-unbound#60]
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound exited with code 1
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format error
unbound      | standard_init_linux.go:228: exec user process caused: exec format

**Comment by chriscrowe** [comment]
Sorry but I don't have nearly enough information here to know how to help you...
