### ISSUE TITLE
Is Unbound actually working?

### ISSUE THREAD

**Issue by wilberfan** [chriscrowe/docker-pihole-unbound#61]
Sorry if this isn't the place for this.  I'm brand-new to unbound, and have only been using pihole for a few weeks.

Followed your tutorial, and pihole is green and 'healthy' in side of portainer.  It's upstream DNS are correctly set as "127.0.0.1#5335".  I'm seeing "OK (forwarded to localhost:5335 INSECURE" entries in the pihole log.  I see "CNAME" and "IP" entries in the pihole Reply column. 

When I try the $dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5335 command the response is "connection timed out; no servers could be reached".   whatismyip.com shows what looks like a legit public IP.   

So, I'm uncertain if unbound is working or not...

**Comment by shahidcodes** [comment]
it does work for me
![image](https://user-images.githubusercontent.com/17620737/128401853-2dfcc859-f4be-4239-be2d-2796d9222221.png)

**Comment by chriscrowe** [comment]
@wilberfan Are you trying to run that command from the pihole itself or from your local client shell? The latter will not work since you're targeting 127.0.0.1 (localhost) -- needs to be run from the pihole shell.

**Comment by wilberfan** [comment]
> @wilberfan Are you trying to run that command from the pihole itself or from your local client shell? The latter will not work since you're targeting 127.0.0.1 (localhost) -- needs to be run from the pihole shell.

It would have been the latter, yes.   I just realized I have no idea how to run a pihole command when pihole is running inside docker...

**Comment by wilberfan** [comment]
> @wilberfan Are you trying to run that command from the pihole itself or from your local client shell? The latter will not work since you're targeting 127.0.0.1 (localhost) -- needs to be run from the pihole shell.

It would have been the latter, yes.   A little googling tells me I need to run the command via docker exec?  I'm struggling a bit with the exact wording of the command, tho:

$ docker exec pihole2 pihole ...

**Comment by wilberfan** [comment]
@chriscrowe Ah, it would have been the latter.   A little googling and I came up with the following command:

`$ docker exec pihole2 dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5335 `

which resulted in something that looks very much like the grab above, and likewise a status: NOERROR when using the sigok. url. 👍  

Usage question:  Sometimes websites are unreachable (I get a DNS lookup error screen)--but if I wait several seconds and refresh, the site will display properly.  Is that typical behavior?  Just hardware (or software) lag with the Pi4 or...?

**Comment by chriscrowe** [comment]
Not normal to get DNS lookup errors, and certainly not normal to see lower block rates. Sounds like there might be a configuration problem with your installation. Closing this as the original problem has been solved.
