### ISSUE TITLE
Pulled new image, can no longer access Pihole GUI; DNS lookups fail

### ISSUE THREAD

**Issue by wilberfan** [chriscrowe/docker-pihole-unbound#69]
Used Portainer to 'recreate' my working pihole-unbound setup while pulling the new image--and I can no longer access pihole gui, and DNS lookups fail.   Portainer indicates "running" (pihole-unbound one-container).  

Are updates inside Portainer not recommended or...?

**Comment by chriscrowe** [comment]
There's some discussion about this `ph_install.sh` error here:

https://discourse.pi-hole.net/t/pihole-portainer-docker-5-8-1-startup-error/48722

Looks like maybe you need to clear out some environment variables?

**Comment by bclevering** [comment]
indeed! that worked for me;

I removed the following variables (from within portainer) and restarted:

  - PIHOLE_INSTALL=/root/ph_install.sh
  - PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
  - PHP_ERROR_LOG=/var/log/lighttpd/error.log
  - S6_LOGGING=0
  - S6_KEEP_ENV=1
  - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
