### ISSUE TITLE
Pihole-Unbound broke when doing update 

### ISSUE THREAD

**Issue by uhsa779** [chriscrowe/docker-pihole-unbound#70]
Doing docker "recreate" - pihole-unbound broke and refuses to start. Below are the logs. Can someone pls help! 

[phole-ubound.txt](https://github.com/chriscrowe/docker-pihole-unbound/files/7122541/phole-ubound.txt)

**Comment by uhsa779** [comment]
I even tried to build a new one - does the same thing. It doesn't work at all. Pls help - without internet on home network.

**Comment by chriscrowe** [comment]
This appears to be the actual error in your output:

```
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 20-start.sh: executing... ,
/start.sh: line 57: /root/ph_install.sh: No such file or directory,
[cont-init.d] 20-start.sh: exited 1., 
```

What is this `ph_install.sh` script? That line of code does not exist in my `20-start.sh` script, did you modify your container? It's really difficult for me to help people to play with the container configs.

**Comment by chriscrowe** [comment]
Proof that that line does not exist in my script:

```
root@pihole:~# grep "ph_install" /etc/cont-init.d/20-start.sh 
root@pihole:~# 
```

**Comment by chriscrowe** [comment]
There's some discussion about this `ph_install.sh` error here:

https://discourse.pi-hole.net/t/pihole-portainer-docker-5-8-1-startup-error/48722

Looks like maybe you need to clear out some environment variables?

**Comment by uhsa779** [comment]
> There's some discussion about this `ph_install.sh` error here:
> 
> https://discourse.pi-hole.net/t/pihole-portainer-docker-5-8-1-startup-error/48722
> 
> Looks like maybe you need to clear out some environment variables?

Thank you - I removed some variables like ServerIP and a couple others - that worked! 
Thank you! I will close this one.

**Comment by uhsa779** [comment]
For docker - what ServerIP should I be keeping? If I remove the "ServerIP" then it defaults to 0.0.0.0 and if I manually put the Docker Virtual IP then in either case there is no DNS resolution.
