### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by arimal199** [chriscrowe/docker-pihole-unbound#71]
There is a new version, please update do dns will work again.

**Comment by brainboost** [comment]
@chriscrowe could you, please, update the image of the one-container solution with latest [v5.4](https://github.com/pi-hole/pi-hole/releases/tag/v5.4) pi-hole image?

**Comment by chriscrowe** [comment]
Will get to this tomorrow night.

**Comment by soundslikecrisps** [comment]
> Will get to this tomorrow night.

Thanks!
I just set this up on a new box last night and was about to start digging into how to build my own docker images. 😛

**Comment by chriscrowe** [comment]
Release `2021.09` is live. 

Please note that I normally wait ~1 week to see if there are issues with the new releases. I broke that rule with the `v5.8.1` and it came back to bit me because there was a show-stopping bug in their upstream release.
