### ISSUE TITLE
No login/logout options

### ISSUE THREAD

**Issue by tbhsm** [chriscrowe/docker-pihole-unbound#88]
Recently, I got this up and running in my Portainer environment recently and I am able to use it as a DNS server for my clients just fine. I appreciate the effort of developing this, thanks!

I'm noticing that compared to my conventional PiHole setup, I'm missing any form of logging in/out. Even the logout button is missing in the PiHole menu. I've tried adding the WEBPASSWORD variable but that did not make a difference. I prefer having some login to prevent local users from accidentally or purposefully change settings. 

How can I enable login?

**Comment by chriscrowe** [comment]
Sorry I'm not familiar with this issue, in fact I didn't even realize it was possible to deploy Pi-Hole without auth. I'm running the version in the repo unmodified and my version requires auth.

**Comment by pluim003** [comment]
> Recently, I got this up and running in my Portainer environment recently and I am able to use it as a DNS server for my clients just fine. I appreciate the effort of developing this, thanks!
> 
> I'm noticing that compared to my conventional PiHole setup, I'm missing any form of logging in/out. Even the logout button is missing in the PiHole menu. I've tried adding the WEBPASSWORD variable but that did not make a difference. I prefer having some login to prevent local users from accidentally or purposefully change settings.
> 
> How can I enable login?

It's been a while, but do you still have this issue? Could you post screenshots how it looks like? I get, as usual, a screen with hardly any information and I can logon, after which I see a bunch more info and I can logout.
