### ISSUE TITLE
Pi-hole Query list multiply requests

### ISSUE THREAD

**Issue by bebbenhorst** [chriscrowe/docker-pihole-unbound#9]
Hi I installed the dockers with pihole

docker compose file:
version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      # - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
    environment:
      ServerIP: 192.168.1.8
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 192.168.1.9
      DNS2: 192.168.1.1
    volumes:
      - /volume1/docker/pihole-unbound/pihole/volume:/etc/pihole:rw
      - /volume1/docker/pihole-unbound/pihole/config/hosts:/etc/hosts:ro
      - /volume1/docker/pihole-unbound/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - /volume1/docker/pihole-unbound/pihole/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.1.8
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    privileged: true
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 192.168.1.9
    restart: always

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.8/30 # 192.168.1.8 and 192.168.1.9

What I thinks is weird but please correct me if Im wrong, the query list on pihole is listing an insane amount of tries to the domain that im trying to reach , it is happening at every domain.

![image](https://user-images.githubusercontent.com/23165240/88933940-5744e080-d280-11ea-84d9-dc9ac80487cb.png)

![image](https://user-images.githubusercontent.com/23165240/88933995-63c93900-d280-11ea-9f85-0d2c4602269e.png)

![image](https://user-images.githubusercontent.com/23165240/88934070-780d3600-d280-11ea-9ef1-a6f6b08bcb5b.png)

Is this normal ??

**Comment by chriscrowe** [comment]
Sorry but I don't have enough information to know whether this is normal-- that said it's not uncommon for DNS queries to be extremely aggressive. This doesn't look out of the ordinary to me, comparing it to my own setup.
