### ISSUE TITLE
How to update PiHole

### ISSUE THREAD

**Issue by bioszombie** [chriscrowe/docker-pihole-unbound#90]
Team,

When logging into the GUI this morning I noted that there is an update for the latest version of Pi-Hole, FTL, and the Web Interface. Checking the docker tag via GitHub I can confirm that I have the latest version.

Docker Tag 2021.10.1 

- Pi-hole v5.6 Update available! 
- FTL v5.11 · Update available!  
- Web Interface v5.8 · Update available!

**To install updates, run `pihole -up`**

I was able to get a shell into the docker container by running
`docker exec -it pihole /bin/bash`

Once a shell was displayed I tried to run
`pihole -up`

But this was not successful. The output that was provided was 

> Function not supported in Docker images

How can I use the shell to run pi-hole -up command? Or get Pihole updated to use the latest version?

EDIT:

Updated issue with the commands I ran.

**Comment by xaabi6** [comment]
Hi @bioszombie, you can check how to do it in pull request [#91](https://github.com/chriscrowe/docker-pihole-unbound/pull/91).

If you decide to do it before the PR gets merged, you must apply the proposed changes and build the docker image afterwards, then, you should be able to use the newly generated image from your docker-compose.

**Comment by bioszombie** [comment]
Much thank you. I will hold for the PR.
