### ISSUE TITLE
Change lighttpd port

### ISSUE THREAD

**Issue by khanduras** [chriscrowe/docker-pihole-unbound#94]
I don't have a PR because I haven't been able to fix it for myself. Is there an easy way to change the HTTP port for lighttpd?

I've been trying 

```
   volumes:
       - /home/pi/docker/pihole/lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro
```
with no success

**Comment by pluim003** [comment]
I tried using this docker-compose.yml-file myself as I wanted to use Unbound and encountered that WEB_PORT is missing.

Put in your .env-file 

WEB_PORT=<whatever_port_you_want_to_use>

and in docker-compose.yml add the following line:

      WEB_PORT: ${WEB_PORT}

under the part of the environment.

I used the same as I used to use. Copied the contents of my pihole-volume to the newly created volume and it's working the same as it used to be.

**Comment by khanduras** [comment]
Hey thanks that worked for me. Cheers
